language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7
  - 7.2

env:
  - TYPO3_VERSION="^7.6.0"
  - TYPO3_VERSION="^8.7.0"

matrix:
  exclude:
    - php: 5.5
      env: TYPO3_VERSION="^8.7.0"
    - php: 5.6
      env: TYPO3_VERSION="^8.7.0"
  include:
    - php: 7.1
      env: SNIFF=1
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - if [[ "$TYPO3_VERSION" && "${TRAVIS_PHP_VERSION:0:3}" < "7.2" ]]; then composer require "typo3/cms:$TYPO3_VERSION" "nimut/testing-framework:^1.1" "phpunit/phpunit:^4.7"; export TYPO3_PATH_WEB=$PWD/.Build/Web; fi
  - if [[ "$TYPO3_VERSION" && "${TRAVIS_PHP_VERSION:0:3}" > "7.1" ]]; then composer require "typo3/cms:$TYPO3_VERSION" "nimut/testing-framework:^3.0.0" "phpunit/phpunit:^6.0.0"; export TYPO3_PATH_WEB=$PWD/.Build/Web; fi
  - git checkout .
  - if [[ "$SNIFF" == "1" ]]; then composer require --dev "friendsofphp/php-cs-fixer" "^1.13"; fi

# before_script:
#   - composer require typo3/cms="$TYPO3_VERSION"
#   # Restore composer.json
#   - git checkout composer.json
#   - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    if [[ "$SNIFF" != "1" ]]; then
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/;
    fi

  - >
    if [[ "$SNIFF" != "1" && "${TRAVIS_PHP_VERSION:0:3}" < "7.0" ]]; then
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | xargs grep --files-without-match -e '<\?php // PHP\s*7' | xargs -n1 -P8 php -l > /dev/null ;
    fi

  - >
    if [[ "$SNIFF" != "1" && "${TRAVIS_PHP_VERSION:0:1}" > "5" ]]; then
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | xargs grep --files-without-match -e '<\?php // PHP\s*7\.[1-9]' | xargs -n1 -P8 php -l > /dev/null ;
    fi
  - >
    if [[ "$SNIFF" != "1" && "${TRAVIS_PHP_VERSION:0:3}" > "7.0" ]]; then
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | xargs grep --files-without-match -e '<\?php // PHP\s*7\.[2-9]' | xargs -n1 -P8 php -l > /dev/null ;
    fi

  - if [[ "$SNIFF" == "1" ]]; then .Build/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --standard=.Build/vendor/vierwd/coding-standard/ForwardMedia Classes/; fi

  # - >
  #   echo;
  #   export typo3DatabaseName="typo3";
  #   export typo3DatabaseHost="localhost";
  #   export typo3DatabaseUsername="root";
  #   export typo3DatabasePassword="";
  #   find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'
