language: php

php:
  - 5.5
  - 5.6
  - 7

env:
  - TYPO3_VERSION="^7.6.0"
  - TYPO3_VERSION="^8.7.0"

matrix:
  exclude:
    - php: 5.5
      env: TYPO3_VERSION="^8.7.0"
    - php: 5.6
      env: TYPO3_VERSION="^8.7.0"
  include:
    - php: 7.1
      env: SNIFF=1
sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - if [[ "$TYPO3_VERSION" ]]; then composer require-typo3-version "$TYPO3_VERSION"; git checkout .; export TYPO3_PATH_ROOT=$PWD/.Build/public; fi
  - if [[ "$SNIFF" == "1" ]]; then composer install; fi

# before_script:
#   - composer require typo3/cms="$TYPO3_VERSION"
#   # Restore composer.json
#   - git checkout composer.json
#   - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

  - >
    if [[ "${TRAVIS_PHP_VERSION:0:3}" < "7.0" ]]; then
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | xargs grep -L -e '<\?php // PHP\s*7' | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \; ;
    fi

  - >
    if [[ "${TRAVIS_PHP_VERSION:0:1}" > "5" ]]; then
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | xargs grep -L -e '<\?php // PHP\s*7\.[1-9]' | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \; ;
    fi
  - >
    if [[ "${TRAVIS_PHP_VERSION:0:3}" > "7.0" ]]; then
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | xargs grep -L -e '<\?php // PHP\s*7\.[2-9]' | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \; ;
    fi

  - if [[ "$SNIFF" == "1" ]]; then .Build/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --standard=.Build/vendor/vierwd/coding-standard/ForwardMedia Classes/; fi

  # - >
  #   echo;
  #   export typo3DatabaseName="typo3";
  #   export typo3DatabaseHost="localhost";
  #   export typo3DatabaseUsername="root";
  #   export typo3DatabasePassword="";
  #   find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'
