language: php

php:
  - 7.2
  - 7.4

env:
  - TYPO3_VERSION="^9.5.0"

jobs:
  include:
    - php: 7.2
      env: SNIFF=1

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - if [[ "$TYPO3_VERSION" ]]; then composer require "typo3/minimal" "$TYPO3_VERSION"; git checkout .; export TYPO3_PATH_WEB=$PWD/.Build/Web; fi
  - if [[ "$SNIFF" == "1" ]]; then composer install; fi

# before_script:
#   - composer require typo3/cms="$TYPO3_VERSION"
#   # Restore composer.json
#   - git checkout composer.json
#   - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running php lint";
    composer run-script phplint

  - >
    echo;
    echo "Running phpstan";
    composer run-script phpstan

  - >
    echo;
    echo "Running unit tests";
    composer run-script unit-test

  # - >
  #   echo;
  #   echo "Running functional tests";
  #   composer run-script test

  - if [[ "$SNIFF" == "1" ]]; then composer run-script phpcs; fi

notifications:
  slack:
    secure: fT4tu3rUGyqLA2nzFdQW3Mf7SfICTnd/ihpG7vmSs9Cii4xBoAW+TatXGjgZPj/ys4Pk/4QVwWZGs+9NV4NTXsbdlsALfYX0Nm1TQ/SAjPcWx9fm6KE2J83kO1VOoGOcPX1BbF5mK4qqzfBj+gdVahXFOI3IgEELLNmnW9tbo7rbJW+UCDJsKKbUjob6VP6PtfH+pb/C3IwsZ5qonUx+U+HmBLA71w99BK/7UgXqhxq+lNY5Q9y1KEstkfwMs6BTzKwqzxBhD9JlTNJBDNVu24T793A8e9mhpiE4Cbtpps0bCoxZeCkn2h0ky/vlKNyx+yPHLVMeLYVOwfubqajYDOjZewNC7qSjJjeBEPAVAZPGd/S+QJ2YntavvO3R/SnaxKkNnd3X/NZ2IrxcrXp2NeUwC8X5VX7Q3qaL/1JmA8cmquigO916g4tO0sitxBNtnVw1KG/P6rzRuC/IAUGYJyLPGendqKeZBEoCGIsfepWCQcTaAtm6EnltF+O9YJmmWgGiwa14G7N9BmpxkgUooN8wcbR4cwZ8lJyj14OixMMr9Ds+/gg/jZF/waTErFnXnBZW2buqQbmWmxXtXFYAcw3cM0es7oLgHEYeXyobq41kXYeo5VP+z6gp0H3E6dY0CJKKAtqkJVrM1XbyFgSptWGYVI9kr/gsz4klIzJH5Eg=
