language: php

php:
  - 7.2
  - 7.4

env:
  - TYPO3_VERSION="^9.5.0"
  - TYPO3_VERSION="^10.4.0"

matrix:
  exclude:
    - php: 7.4
      env: TYPO3_VERSION="^10.4.0"
  include:
    - php: 7.2
      env: SNIFF=1
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  - if [[ "$TYPO3_VERSION" ]]; then composer require "typo3/minimal" "$TYPO3_VERSION"; git checkout .; export TYPO3_PATH_WEB=$PWD/.Build/Web; fi
  - if [[ "$SNIFF" == "1" ]]; then composer install; fi

# before_script:
#   - composer require typo3/cms="$TYPO3_VERSION"
#   # Restore composer.json
#   - git checkout composer.json
#   - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

  - >
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | xargs grep --files-without-match --regexp '<\?php // PHP\s*7\.[3-9]' | xargs -n1 -P8 php -l > /dev/null ;

  - if [[ "$SNIFF" == "1" ]]; then .Build/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --standard=.Build/vendor/vierwd/coding-standard/ForwardMedia Classes/; fi

  # - >
  #   echo;
  #   export typo3DatabaseName="typo3";
  #   export typo3DatabaseHost="localhost";
  #   export typo3DatabaseUsername="root";
  #   export typo3DatabasePassword="";
  #   find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors  -c .Build/vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml {}'

notifications:
  slack:
    secure: fT4tu3rUGyqLA2nzFdQW3Mf7SfICTnd/ihpG7vmSs9Cii4xBoAW+TatXGjgZPj/ys4Pk/4QVwWZGs+9NV4NTXsbdlsALfYX0Nm1TQ/SAjPcWx9fm6KE2J83kO1VOoGOcPX1BbF5mK4qqzfBj+gdVahXFOI3IgEELLNmnW9tbo7rbJW+UCDJsKKbUjob6VP6PtfH+pb/C3IwsZ5qonUx+U+HmBLA71w99BK/7UgXqhxq+lNY5Q9y1KEstkfwMs6BTzKwqzxBhD9JlTNJBDNVu24T793A8e9mhpiE4Cbtpps0bCoxZeCkn2h0ky/vlKNyx+yPHLVMeLYVOwfubqajYDOjZewNC7qSjJjeBEPAVAZPGd/S+QJ2YntavvO3R/SnaxKkNnd3X/NZ2IrxcrXp2NeUwC8X5VX7Q3qaL/1JmA8cmquigO916g4tO0sitxBNtnVw1KG/P6rzRuC/IAUGYJyLPGendqKeZBEoCGIsfepWCQcTaAtm6EnltF+O9YJmmWgGiwa14G7N9BmpxkgUooN8wcbR4cwZ8lJyj14OixMMr9Ds+/gg/jZF/waTErFnXnBZW2buqQbmWmxXtXFYAcw3cM0es7oLgHEYeXyobq41kXYeo5VP+z6gp0H3E6dY0CJKKAtqkJVrM1XbyFgSptWGYVI9kr/gsz4klIzJH5Eg=
