<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vierwd_base"
 *
 * Auto generated by Extension Builder 2015-02-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FORWARD MEDIA TYPO3 Basis',
	'description' => 'Adds some database configs during installation process',
	'category' => 'distribution',
	'author' => 'Robert Vock',
	'author_email' => 'robert.vock@4wdmedia.de',
	'author_company' => 'FORWARD MEDIA',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 1,
	'lockType' => '',
	'version' => '1.1.1',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'gridelements' => '*',
		),
	),
	'_md5_values_when_last_written' => 'a:3:{s:12:"ext_icon.gif";s:4:"59e6";s:17:"ext_localconf.php";s:4:"d4ac";s:16:"typo3version.php";s:4:"9131";}',
);

?>