<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vierwd_base"
 *
 * Auto generated by Extension Builder 2015-02-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'FORWARD MEDIA TYPO3 Basis',
	'description' => 'Adds some database configs during installation process',
	'category' => 'distribution',
	'author' => 'Robert Vock',
	'author_email' => 'robert.vock@4wdmedia.de',
	'author_company' => 'FORWARD MEDIA',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'lockType' => '',
	'version' => '13.0.0',
	'constraints' => [
		'depends' => [],
		'conflicts' => [],
		'suggests' => [
			'container' => '*',
		],
	],
];
