services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vierwd\VierwdBase\Backend\:
    resource: '../Classes/Backend/*'

  Vierwd\VierwdBase\ContentElements\ModifyUserGroups:
    tags:
      - name: event.listener
        identifier: 'vierwdModifyGroups'
        event: TYPO3\CMS\Core\Authentication\Event\AfterGroupsResolvedEvent

  Vierwd\VierwdBase\Controller\:
    resource: '../Classes/Controller/*'

  Vierwd\VierwdBase\Backend\GetButtonsHook:
    tags:
      - name: event.listener
        identifier: 'vierwdSaveAndClose'
        event: TYPO3\CMS\Backend\Template\Components\ModifyButtonBarEvent

  Vierwd\VierwdBase\Resource\CacheBuster:
    tags:
      - name: event.listener
        identifier: 'vierwdResourceCacheBuster'
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent
  Vierwd\VierwdBase\Resource\DuplicateFiles:
    tags:
      - name: event.listener
        identifier: 'vierwdResourceDuplicateFiles'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedEvent
  Vierwd\VierwdBase\Hooks\ContentElements:
    tags:
      - name: event.listener
        identifier: 'vierwdCustomContentElements'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent
  Vierwd\VierwdBase\Hooks\IndexFilesAfterImport:
    tags:
      - name: event.listener
        identifier: 'vierwdIndexFilesAfterImport'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionFilesHaveBeenImportedEvent
  # Add Link Icons https://trello.com/c/V7FscJkV/
  Vierwd\VierwdBase\Frontend\TypolinkIcons:
    tags:
      - name: event.listener
        identifier: 'vierwdTypolinkIcons'
        event: TYPO3\CMS\Frontend\Event\AfterLinkIsGeneratedEvent
        method: 'addLinkIcon'
  Vierwd\VierwdBase\Frontend\PostProcessHTML:
    tags:
      - name: event.listener
        identifier: 'vierwdPostProcessHTML'
        method: processCached
        event: TYPO3\CMS\Frontend\Event\AfterCacheableContentIsGeneratedEvent

  Vierwd\VierwdBase\Console\Command\PostComposerCommand:
    tags:
      - name: 'console.command'
        command: 'vierwd:post-composer'
        schedulable: false
        # unfortunately runLevel is not supported anymore
        # runLevel: Helhum\Typo3Console\Core\Booting\RunLevel::LEVEL_COMPILE
  Vierwd\VierwdBase\Console\Command\Database\ExportCommand:
    tags:
      - name: 'console.command'
        command: 'vierwd:database:export'
        schedulable: false
        # unfortunately runLevel is not supported anymore
        # runLevel: Helhum\Typo3Console\Core\Booting\RunLevel::LEVEL_MINIMAL
  Vierwd\VierwdBase\Console\Command\Database\ImportCommand:
    tags:
      - name: 'console.command'
        command: 'vierwd:database:import'
        schedulable: false
        # unfortunately runLevel is not supported anymore
        # runLevel: Helhum\Typo3Console\Core\Booting\RunLevel::LEVEL_COMPILE
  Vierwd\VierwdBase\Console\Command\Database\KbImportCommand:
    tags:
      - name: 'console.command'
        command: 'vierwd:database:kb-import'
        schedulable: false
        # unfortunately runLevel is not supported anymore
        # runLevel: Helhum\Typo3Console\Core\Booting\RunLevel::LEVEL_MINIMAL
  Vierwd\VierwdBase\Console\Command\Database\LastChangeCommand:
    tags:
      - name: 'console.command'
        command: 'vierwd:database:last-change'
        schedulable: false
  Vierwd\VierwdBase\Console\Command\ListWordsCommand:
    tags:
      - name: 'console.command'
        command: 'vierwd:list-words'
        schedulable: false
  Vierwd\VierwdBase\Console\Command\RsyncCommand:
    tags:
      - name: 'console.command'
        command: 'vierwd:rsync:down'
        schedulable: false
  Vierwd\VierwdBase\Console\Command\PublishCommand:
    tags:
      - name: 'console.command'
        command: 'vierwd:publish'
        schedulable: false
