services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vierwd\VierwdBase\Backend\:
    resource: '../Classes/Backend/*'

  Vierwd\VierwdBase\Console\:
    resource: '../Classes/Console/*'

  Vierwd\VierwdBase\ContentElements\:
    resource: '../Classes/ContentElements/*'

  Vierwd\VierwdBase\Controller\:
    resource: '../Classes/Controller/*'

  Vierwd\VierwdBase\Controller\:
    resource: '../Classes/Resource/{IndexFilesAfterImport}.php'

  Vierwd\VierwdBase\Resource\:
    resource: '../Classes/Resource/{CacheBuster,DuplicateFiles}.php'

  Vierwd\VierwdBase\Hooks\ContentElements:
    tags:
      - name: event.listener
        identifier: 'vierwdCustomContentElements'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

  # Add Link Icons https://trello.com/c/V7FscJkV/
  Vierwd\VierwdBase\Frontend\TypolinkIcons:
    tags:
      - name: event.listener
        identifier: 'vierwdTypolinkIcons'
        event: TYPO3\CMS\Frontend\Event\AfterLinkIsGeneratedEvent
        method: 'addLinkIcon'
  Vierwd\VierwdBase\Frontend\PostProcessHTML:
    tags:
      - name: event.listener
        identifier: 'vierwdPostProcessHTML'
        method: processCached
        event: TYPO3\CMS\Frontend\Event\AfterCacheableContentIsGeneratedEvent
